### ISSUE TITLE
Reduce minimum SDK version

### ISSUE THREAD

**Issue by segunfrancis** [sakshampruthi/custom-loading-screen#2]
Can you reduce your minimum SDK version so that it can be used by projects targeting lower than API level 23?

**Comment by sakshampruthi** [comment]
@segunfrancis Since I am using viewBinding in this project, it has a restriction of min Api to be 23

**Comment by segunfrancis** [comment]
I don't think so. I copied your library module into an android project and reduced the minSdk to 21, it worked!
